### ISSUE TITLE
Readme usage on example is out of date for version 0.1.0

### ISSUE THREAD

**Issue by themmer** [ionic-team/react-native-ionic-portals#28]
Can we update the readme with the latest usage on PortalView?
https://github.com/ionic-team/react-native-ionic-portals/blob/main/README.md

PortalView now uses `portal` object instead of the `name` string property
See example in codebase: example/App.tsx

fyi @Steven0351

**Comment by Steven0351** [comment]
In the spirit of how all the other Portals repos operate, I've removed documentation from the README with links to the documentation we have hosted so we don't have to duplicate effort across multiple repos to keep docs up to date
