### ISSUE TITLE
Getting error "Project with path ':capacitor-android' could not be found in project"

### ISSUE THREAD

**Issue by naseertkxel** [ionic-team/react-native-ionic-portals#30]
Hi,

I'm trying to configure a capacitor plugin ( not a core or community ) in **React-Native** for **android** but getting an error. 

> Project with path ':capacitor-android' could not be found in project ':capacitor-biometric-auth'

I have followed the docs to add another plugin [Docs](https://ionic.io/docs/portals/how-to/using-a-capacitor-plugin#other-plugins)

Here are my settings.gradle

```
rootProject.name = 'yauCoachPortal'

include ':capacitor-biometric-auth'
project(':capacitor-biometric-auth').projectDir = new File('../webapp/node_modules/@aparajita/capacitor-biometric-auth/android')

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/react-native-gradle-plugin')

if (settings.hasProperty("newArchEnabled") && settings.newArchEnabled == "true") {
    include(":ReactAndroid")
    project(":ReactAndroid").projectDir = file('../node_modules/react-native/ReactAndroid')
}
```

And app/build.gradle

```
dependencies {

    implementation project(':capacitor-biometric-auth')
    implementation 'io.ionic:portals:0.5.0'

    implementation fileTree(dir: "libs", include: ["*.jar"])

    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    //other stuff
}
```

I have tried to configure both `npm i capacitor-native-biometric` and `npm i capacitor-biometric-auth`

`"@ionic/portals-react-native": "^0.0.4"`

I'm I missing something while configuring for android? If so please suggest to me the missing step(s).

**Note**:  iOS get configured by following the docs.

**Comment by naseertkxel** [comment]
Hi, @carlpoole! Is there any additional step that needs to be followed for capacitor plugins that are not listed in the core or community documentation?

**Comment by carlpoole** [comment]
The plugin is expecting to reference local Capacitor code in the project which it cannot find. This usually isn't an issue in Capacitor apps but since this is a Portals app for React Native I would try the following:

- Locate the `build.gradle` file (https://github.com/aparajita/capacitor-biometric-auth/blob/main/android/build.gradle) for the linked plugin code and replace the following line in the dependencies

```
implementation project(':capacitor-android')
```

with 

```
implementation "com.capacitorjs:core:3.7.0"
```

This will have it use the published Capacitor Core native Android dependency designed for Portals use and should resolve the problem. Please let me know if that works!

**Comment by naseertkxel** [comment]
@carlpoole,  I'm on it and will share the outcome here.

**Comment by Steven0351** [comment]
Are you configuring the Portal in native code or in React? If you're doing the plugin registration in React your Portal object needs to include an `androidPlugins` field like this:
```javascript
const portal = {
  name: "foo",
  androidPlugins: ["com.aparajita.capacitor.biometricauth.BiometricAuthNative"] // <- full classpath of the native android plugin is required
}
```

If you're doing the plugin configuration in native code, you need to explicitly add it as part of the PortalBuilder:
```java
import com.aparajita.capacitor.biometricauth.BiometricAuthNative;

builder.addPlugin(BiometricAuthNative.class)
```

**Comment by naseertkxel** [comment]
@carlpoole @Steven0351 appreciated your timely feedback. I'm able to make it work now.

**Comment by Steven0351** [comment]
@naseertkxel could you share which method you used to override the capacitor plugin?

**Comment by naseertkxel** [comment]
@Steven0351 I have added the full classpath of the native android plugin `androidPlugins` array.
From docs, it seems this is only needed when dealing with cor plugins. But after adding a full classpath `androidPlugins`'s array app is working as expected.
