### ISSUE TITLE
AndroidPortalView not found in the UIManager

### ISSUE THREAD

**Issue by malkomich** [ionic-team/react-native-ionic-portals#37]
### Steps to reproduce:
- Add "@ionic/portals-react-native": "0.3.0" dependency to any React Native project.
- Import anything from "@ionic/portals-react-native" lib
- Execute in Android emulator or device

I am having the following error:
```
Invariant Violation: requireNativeComponent: "AndroidPortalView" was not found in the UIManager.

This error is located at:
    in AndroidPortalView (created by PortalView)
    in PortalView (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

I also tried in [https://snack.expo.dev](https://snack.expo.dev), just to check if there were something wrong with my new project (I was just bootstraping a new project, so I doubted it could be the reason).
Once I imported anything from the library, I got the following error:
```
(0 , r(...).requireNativeComponent) is not a function
  Evaluating @ionic/portals-react-native.js
  Evaluating App.js
  Loading App.js
TypeError: (0 , r(...).requireNativeComponent) is not a function
    at Array.eval (@ionic/portals-react-native.js:3:7644)
    at r (@ionic/portals-react-native.js:3:7868)
    at eval (@ionic/portals-react-native.js:3:8233)
    at eval (@ionic/portals-react-native.js:3:10464)
    at eval (@ionic/portals-react-native.js:3:10509)
    at Object.eval (@ionic/portals-react-native.js:3:10515)
    at eval (@ionic/portals-react-native.js:8:4)
    at eval (@ionic/portals-react-native.js:9:3)
    at eval (<anonymous>)
    at https://snack-web-player.s3.us-west-1.amazonaws.com/v2/46/static/js/app.e3f1aedc.chunk.js:1:8273
```

**Comment by Steven0351** [comment]
Is your project an Expo project? If so, Expo isn't currently supported without ejecting

**Comment by malkomich** [comment]
Thanks @Steven0351 for your reply!

Exactly, the project is an Expo project, so that is the reason then. I just tried with a plain old React Native application and the error was gone.

Anyways, I deduce from your answer that it is considered for future releases to support it, right?

**Comment by Steven0351** [comment]
It's not currently on our road map. We require the ability to depend on native libraries and implementing the modules using custom native code. We found that makes our library incompatible with Expo when this module was first implemented.

**Comment by malkomich** [comment]
I understand. Thank you for the explanation @Steven0351 =D

I will start using it no matter I have to abandon Expo for my project, I find Ionic Portals a great tool and I hope to see it grow and get more integrations included. You guys are doing an awesome job!
